source "https://rubygems.org"
gem "jekyll", "~> 4.2"
# Add plugins:
gem "jekyll-feed"
gem "jekyll-archives-v2"
gem "jekyll-sitemap"
gem "jekyll-email-protect"
gem "jekyll-get-json"
gem "jekyll-imagemagick"
gem "jekyll-jupyter-notebook"
gem "jekyll-link-attributes"
gem "jekyll-minifier"
gem "jekyll-paginate-v2"
gem "jekyll-regex-replace"
gem "jekyll-tabs"
gem "jekyll-scholar"
gem "jekyll-toc"
gem "jemoji"
gem "jekyll-twitter-plugin"
